#!/usr/bin/env node
/**
 * Populate .env.local from whichever Supabase project this repo is linked to.
 *
 *   npm run env:pull
 *
 * Why: keys should never be pasted by hand or committed, and one machine may
 * work across several projects with different credentials. The Supabase CLI
 * already models this — a single `supabase login` authenticates you, and each
 * repo records its own project in supabase/.temp/project-ref (or
 * supabase/config.toml). This script reads that ref and asks the CLI for that
 * project's anon key, so switching projects is just switching directories.
 *
 * Prerequisites:
 *   npx supabase login        (once per machine)
 *   npx supabase link --project-ref <ref>   (once per repo, if not linked)
 *
 * Existing non-Supabase lines in .env.local are preserved.
 */

import { readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { resolve, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const run = promisify(execFile);
const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const ENV_PATH = join(ROOT, '.env.local');

function fail(message, hint) {
  console.error(`\n  ✖ ${message}`);
  if (hint) console.error(`\n    ${hint}`);
  console.error('');
  process.exit(1);
}

/** Read the linked project ref from the CLI's state, then config.toml. */
async function readProjectRef() {
  const tempRef = join(ROOT, 'supabase', '.temp', 'project-ref');
  if (existsSync(tempRef)) {
    const ref = (await readFile(tempRef, 'utf8')).trim();
    if (ref) return ref;
  }

  const configPath = join(ROOT, 'supabase', 'config.toml');
  if (existsSync(configPath)) {
    const config = await readFile(configPath, 'utf8');
    const match = config.match(/^\s*project_id\s*=\s*"([^"]+)"/m);
    if (match) return match[1];
  }

  return null;
}

async function fetchAnonKey(ref) {
  let stdout;
  try {
    ({ stdout } = await run(
      'npx',
      ['--yes', 'supabase', 'projects', 'api-keys', '--project-ref', ref, '--output', 'json'],
      { cwd: ROOT, maxBuffer: 1024 * 1024 },
    ));
  } catch (err) {
    const detail = `${err.stderr ?? ''}${err.stdout ?? ''}`;
    if (/not logged in|Access token not provided|login/i.test(detail)) {
      fail(
        'The Supabase CLI is not authenticated.',
        'Run:  npx supabase login\n    then re-run:  npm run env:pull',
      );
    }
    fail(
      `Could not read API keys for project "${ref}".`,
      detail.trim().split('\n').slice(0, 4).join('\n    ') ||
        'Check that the project ref is correct and your account can access it.',
    );
  }

  let keys;
  try {
    keys = JSON.parse(stdout);
  } catch {
    fail('Unexpected output from the Supabase CLI (not JSON).');
  }

  // The CLI returns [{ name: 'anon', api_key: '…' }, { name: 'service_role', … }]
  const anon = keys.find((k) => k.name === 'anon' || k.name === 'publishable');
  if (!anon?.api_key) {
    fail(`No anon key returned for project "${ref}".`);
  }
  return anon.api_key;
}

/** Keep any lines the user added that this script does not own. */
async function preservedLines() {
  if (!existsSync(ENV_PATH)) return [];
  const current = await readFile(ENV_PATH, 'utf8');
  const owned = /^(VITE_SUPABASE_URL|VITE_SUPABASE_ANON_KEY)=/;
  return current
    .split('\n')
    .filter((line) => line.trim() && !line.trim().startsWith('#') && !owned.test(line));
}

async function main() {
  const ref = await readProjectRef();
  if (!ref) {
    fail(
      'This repo is not linked to a Supabase project.',
      'Run:  npx supabase link --project-ref <your-project-ref>',
    );
  }

  console.log(`  Linked project: ${ref}`);
  const anonKey = await fetchAnonKey(ref);
  const extras = await preservedLines();

  const body = [
    '# Generated by `npm run env:pull` — do not commit.',
    '# Re-run that command after switching or re-linking projects.',
    '',
    `VITE_SUPABASE_URL=https://${ref}.supabase.co`,
    `VITE_SUPABASE_ANON_KEY=${anonKey}`,
    ...(extras.length ? ['', '# Preserved from your previous .env.local', ...extras] : []),
    '',
  ].join('\n');

  await writeFile(ENV_PATH, body, 'utf8');
  console.log(`  ✔ Wrote .env.local (${extras.length} existing line(s) preserved)\n`);
}

main().catch((err) => {
  console.error('[env:pull] failed:', err);
  process.exit(1);
});
